### ISSUE TITLE
Unhandled exception in WASM builds

### ISSUE THREAD

**Issue by wihrl** [Cryru/Emotion#71]
Seems rendering related.

Exception:
![image](https://user-images.githubusercontent.com/57505542/124290764-1cb08b80-db54-11eb-86d2-6ae19dae0789.png)

Source:
![image](https://user-images.githubusercontent.com/57505542/124290728-16221400-db54-11eb-81d4-6b7c394b6a37.png)

**Comment by Cryru** [comment]
This was broken in 3b57a60 due to the usage of BufferSubData which is implemented on the JS side of the webgl driver but not on the Blazor side. Since no tests run for the web version this went uncaught.

Thankfully it was an easy fix :)
